const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '../apps/admin/node_modules/playwright');
const { pathToFileURL } = require('node:url');
const fs = require('node:fs');
(async()=>{
 fs.mkdirSync('artifacts/design-review',{recursive:true});
 const browser=await chromium.launch({...(process.platform==='win32'?{channel:'msedge'}:{}),headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:720}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(require('node:path').resolve('design-prototype/index.html')).href);
 const assert=(v,m)=>{if(!v)throw Error(m);console.log('PASS '+m)};
 assert(await page.locator('.product').count()===32,'32 lauk available');
 assert(await page.locator('.products').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length)===4,'four columns at 1280');
 assert(await page.locator('.brand img').evaluate(e=>e.complete&&e.naturalWidth>0),'application logo loaded');
 assert(await page.locator('.rail').evaluate(e=>e.getBoundingClientRect().height<90),'navigation at top');
 await page.screenshot({path:'artifacts/design-review/01-catalog-1280.png'});
 await page.locator('[data-product="Lauk0"]').click();await page.locator('[data-product="Lauk1"]').click();await page.locator('[data-plus="Lauk0"]').click();
 assert(await page.locator('#total').textContent()==='Rp3.000','instant quantity and total');
 await page.screenshot({path:'artifacts/design-review/02-cart-1280.png'});
 await page.locator('#pay').click();assert(await page.locator('#complete').isDisabled(),'insufficient cash blocked');
 await page.locator('[data-cash="50000"]').click();assert(await page.locator('#change').textContent()==='Kembalian Rp47.000','cash change correct');
 await page.screenshot({path:'artifacts/design-review/03-payment.png'});
 await page.locator('#complete').click();await page.locator('#close').click();
 await page.locator('[data-nav="history"]').click();assert(await page.locator('.listrow').count()===1,'completed sale reaches history');
 await page.screenshot({path:'artifacts/design-review/04-history.png'});
 await page.locator('[data-nav="sell"]').click();await page.setViewportSize({width:900,height:620});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=900),'no horizontal overflow at 900');
 await page.screenshot({path:'artifacts/design-review/05-small.png'});
 for(const state of ['offline','syncing','pending','loading','error','printer','online'])await page.locator('#state').selectOption(state);
 await page.setViewportSize({width:1366,height:768});
 await page.locator('[data-nav="settings"]').click();
 await page.locator('#previewQris').click();
 assert(await page.locator('#toast').evaluate(e=>{const b=e.getBoundingClientRect();return getComputedStyle(e).animationName==='slide-in'&&getComputedStyle(e).bottom==='48px'}),'QRIS bottom-left slide animation');
 await page.screenshot({path:'artifacts/design-review/06-qris.png'});
 await page.locator('#previewReceipt').click();
 assert(await page.locator('.receipt img').evaluate(e=>e.complete&&e.naturalWidth>0),'full receipt logo loaded');
 assert((await page.locator('.receipt').innerText()).includes('@asoyyy_group'),'new Instagram on receipt');
 await page.screenshot({path:'artifacts/design-review/07-receipt.png'});
 assert(errors.length===0,'no JavaScript errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
